### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Swivelgames** [webpack/grunt-webpack#56] opened 2015-10-11 08:21 UTC
After updating to the latest version of `grunt-webpack`, my builds stopped working. I started getting an error every time I tried to build:

```sh
Segmentation fault: 11
```

After resorting to ripping everything out of my `Gruntfile.js`, I was left with the following when it finally went away:

```js
module.exports = function(grunt) {
	grunt.initConfig({
		pkg: grunt.file.readJSON('package.json')/*,
	});

//	grunt.loadNpmTasks('grunt-webpack');
};
```

After commenting out `grunt-webpack`, I was finally able to complete my grunt build.

I'm running OSX 10.10.5. Other info:

```sh
$ node -v
v4.0.0
$ npm -v
2.14.2
$ grunt -V
grunt-cli v0.1.13
grunt v0.4.5
```

```json
  "devDependencies": {
    "webpack": "1.12.2",
    "jsx-loader": "0.13.2",
    "style-loader": "0.12.4",
    "css-loader": "0.19.0",
    "json-loader": "0.5.3",
    "grunt": "0.4.5",
    "grunt-webpack": "1.0.11",
    "grunt-contrib-less": "0.11.3",
    "grunt-contrib-watch": "0.6.1"
  },
```

Output of Final Discovery Attempts:
```sh
$ grunt --force
Segmentation fault: 11
$ grunt --force
Warning: Task "default" not found. Used --force, continuing.

Done, but with warnings.
```

After discovering what the issue was, I decided to try verbose to see if I could find out where it was failing, and I got the following output:

```sh
$ grunt -v
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK

Registering "grunt-webpack" local Npm module tasks.
Reading /********/node_modules/grunt-webpack/package.json...OK
Parsing /********/node_modules/grunt-webpack/package.json...OK
Segmentation fault: 11
```

**Comment by Swivelgames** [comment] 2015-10-11 08:25
Tried to back down to `1.0.10`, but am still getting a `Segmentation fault`. After trying to back down to the original version I had, I noticed that you guys only keep `Current Version - 1` in your repo, so now I'm blocked on a major deliverable.

**Comment by danez** [comment] 2016-10-23 19:16
If this is still a problem please report back. Closing for now, as I could not reproduce.

**Closed by danez** 2016-10-23 19:16 UTC
